/**
 * Avatar Component - Main Entry Point
 * Generated by Emadocs Framework
 */

// Import all variants
import './variant-1/script.js';
import './variant-2/script.js';
import './variant-3/script.js';
import './variant-4/script.js';
import './variant-5/script.js';

// Export component
export { default as Avatar } from './avatar.ema';

// Component registry
if (typeof window !== 'undefined' && window.EmadocsComponents) {
  window.EmadocsComponents.register('Avatar', {
    name: 'Avatar',
    variants: ['minimal', 'neo', 'soft', 'glass', 'premium'],
    defaultVariant: 'minimal'
  });
}

console.log('Avatar component loaded with 5 variants');
