/**
 * Autocomplete Component - Main Entry Point
 * Generated by Emadocs Framework
 */

// Import all variants
import './variant-1/script.js';
import './variant-2/script.js';
import './variant-3/script.js';
import './variant-4/script.js';
import './variant-5/script.js';

// Export component
export { default as Autocomplete } from './autocomplete.ema';

// Component registry
if (typeof window !== 'undefined' && window.EmadocsComponents) {
  window.EmadocsComponents.register('Autocomplete', {
    name: 'Autocomplete',
    variants: ['minimal', 'neo', 'soft', 'glass', 'premium'],
    defaultVariant: 'minimal'
  });
}

console.log('Autocomplete component loaded with 5 variants');
