/**
 * Heatmap Component - Main Entry Point
 * Generated by Emadocs Framework
 */

// Import all variants
import './variant-1/script.js';
import './variant-2/script.js';
import './variant-3/script.js';
import './variant-4/script.js';
import './variant-5/script.js';

// Export component
export { default as Heatmap } from './heatmap.ema';

// Component registry
if (typeof window !== 'undefined' && window.EmadocsComponents) {
  window.EmadocsComponents.register('Heatmap', {
    name: 'Heatmap',
    variants: ['minimal', 'neo', 'soft', 'glass', 'premium'],
    defaultVariant: 'minimal'
  });
}

console.log('Heatmap component loaded with 5 variants');
