/**
 * Navigate Component - Main Entry Point
 * Generated by Emadocs Framework
 */

// Import all variants
import './variant-1/script.js';
import './variant-2/script.js';
import './variant-3/script.js';
import './variant-4/script.js';
import './variant-5/script.js';

// Export component
export { default as Navigate } from './navigate.ema';

// Component registry
if (typeof window !== 'undefined' && window.EmadocsComponents) {
  window.EmadocsComponents.register('Navigate', {
    name: 'Navigate',
    variants: ['minimal', 'neo', 'soft', 'glass', 'premium'],
    defaultVariant: 'minimal'
  });
}

console.log('Navigate component loaded with 5 variants');
